version: '3'
networks:
  usuarios_network:
    driver: bridge
  eventos_network:
    driver: bridge
  vendas_network:
    driver: bridge

services:
  frontend:
    restart: always
    build: ./frontend
    working_dir: /home/node/app
    ports:
    - "3000:3000"
    networks:
    - usuarios_network
    - eventos_network
    - vendas_network

  kafka:
    image: spotify/kafka:latest
    ports:
    - "9092:9092"
    - "2181:2181"
    hostname: kafka
    environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
      AUTO_CREATE_TOPICS: "true"
    networks: 
    - usuarios_network
    - eventos_network
    - vendas_network
    command: >
      bash -c
      "(sleep 15s &&
      /opt/kafka_2.11-0.10.1.0/bin/kafka-topics.sh
      --create
      --zookeeper
      localhost:2181 --replication-factor 1 --partitions 1
      --topic usuarios_topic
      && 
      /opt/kafka_2.11-0.10.1.0/bin/kafka-topics.sh
      --create
      --zookeeper
      localhost:2181 --replication-factor 1 --partitions 2
      --topic eventos_topic
      && 
      /opt/kafka_2.11-0.10.1.0/bin/kafka-topics.sh
      --create
      --zookeeper
      localhost:2181 --replication-factor 1 --partitions 2
      --topic vendas_topic &) && (supervisord -n)"
  
  usuarios-mysql:
    container_name: usuarios-mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: usuarios
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql123
    ports: 
    - "3306:3306"
    networks:
    - usuarios_network
    restart: always
  
  usuarios-app:
    restart: always
    build: ./usuarios
    working_dir: /usuarios
    ports:
    - "8080:8080"
    networks:
    - usuarios_network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://usuarios-mysql:3306/usuarios?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: mysql
      SPRING_DATASOURCE_PASSWORD: mysql123
      SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS: kafka:9092
      USUARIOS_TOPIC: usuarios_topic
      SERVER_PORT: 8080
    depends_on:
      - usuarios-mysql
      - kafka

  eventos-mysql:
    container_name: eventos-mysql
    image: mysql/mysql-server:5.7
    environment:
     MYSQL_DATABASE: eventos
     MYSQL_ROOT_PASSWORD: mysql
     MYSQL_ROOT_HOST: '%'
     MYSQL_USER: mysql
     MYSQL_PASSWORD: mysql123
    ports:
    - "3307:3306"
    networks: 
    - eventos_network
    restart: always
  
  eventos-app:
    restart: always
    build: ./eventos
    working_dir: /eventos
    ports:
    - "8081:8080"
    networks: 
    - eventos_network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://eventos-mysql:3306/eventos?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: mysql
      SPRING_DATASOURCE_PASSWORD: mysql123
      SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS: kafka:9092
      EVENTOS_TOPIC: eventos_topic
      SERVER_PORT: 8080
    depends_on:
      - eventos-mysql
      - kafka

  vendas-mysql:
    container_name: vendas-mysql
    image: mysql/mysql-server:5.7
    environment:
     MYSQL_DATABASE: vendas
     MYSQL_ROOT_PASSWORD: mysql
     MYSQL_ROOT_HOST: '%'
     MYSQL_USER: mysql
     MYSQL_PASSWORD: mysql123
    ports:
    - "3308:3306"
    networks: 
    - vendas_network
    restart: always
  
  vendas-app:
    restart: always
    build: ./vendas
    working_dir: /vendas
    ports:
    - "8082:8080"
    networks: 
    - vendas_network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://vendas-mysql:3306/vendas?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: mysql
      SPRING_DATASOURCE_PASSWORD: mysql123
      SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS: kafka:9092
      VENDAS_TOPIC: vendas_topic
      SERVER_PORT: 8080
    depends_on:
      - vendas-mysql
      - kafka